spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/primarydb?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:postgresql://localhost:5432/primarydb
    name:  primarydb
    username: root
    password: liyahong
#    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  datasource2:
    url: jdbc:mariadb://localhost:3306/secondarydb?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:postgresql://localhost:5432/secondarydb
    name:  secondarydb
    username: root
    password: liyahong
#    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.example.demo.hibernate.dialect.MariaDB103Dialect
#
#logging:
#  level.org.hibernate: debug